FROM golang:1.13

WORKDIR /F2

COPY go.mod go.sum ./

RUN go mod download

COPY F2/main.go ./

RUN go get github.com/FranZk9/lab3Distribuidos/proto

RUN go build -o F2_bin .

ENTRYPOINT [ "./F2_bin" ]