FROM golang:1.13

WORKDIR /vanguardia
COPY go.mod go.sum ./

RUN go mod download

COPY vanguardia/main.go ./

RUN go get github.com/FranZk9/lab3Distribuidos/proto

RUN go build -o Vanguardia_bin .

ENTRYPOINT [ "./Vanguardia_bin" ]