// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/base.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mensaje struct {
	Nombre               string   `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mensaje) Reset()         { *m = Mensaje{} }
func (m *Mensaje) String() string { return proto.CompactTextString(m) }
func (*Mensaje) ProtoMessage()    {}
func (*Mensaje) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc17cb2a757cc3a9, []int{0}
}

func (m *Mensaje) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mensaje.Unmarshal(m, b)
}
func (m *Mensaje) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mensaje.Marshal(b, m, deterministic)
}
func (m *Mensaje) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mensaje.Merge(m, src)
}
func (m *Mensaje) XXX_Size() int {
	return xxx_messageInfo_Mensaje.Size(m)
}
func (m *Mensaje) XXX_DiscardUnknown() {
	xxx_messageInfo_Mensaje.DiscardUnknown(m)
}

var xxx_messageInfo_Mensaje proto.InternalMessageInfo

func (m *Mensaje) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

type CommandAddUpdate struct {
	NombreSector         string   `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase           string   `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	Valor                string   `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandAddUpdate) Reset()         { *m = CommandAddUpdate{} }
func (m *CommandAddUpdate) String() string { return proto.CompactTextString(m) }
func (*CommandAddUpdate) ProtoMessage()    {}
func (*CommandAddUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc17cb2a757cc3a9, []int{1}
}

func (m *CommandAddUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandAddUpdate.Unmarshal(m, b)
}
func (m *CommandAddUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandAddUpdate.Marshal(b, m, deterministic)
}
func (m *CommandAddUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandAddUpdate.Merge(m, src)
}
func (m *CommandAddUpdate) XXX_Size() int {
	return xxx_messageInfo_CommandAddUpdate.Size(m)
}
func (m *CommandAddUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandAddUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CommandAddUpdate proto.InternalMessageInfo

func (m *CommandAddUpdate) GetNombreSector() string {
	if m != nil {
		return m.NombreSector
	}
	return ""
}

func (m *CommandAddUpdate) GetNombreBase() string {
	if m != nil {
		return m.NombreBase
	}
	return ""
}

func (m *CommandAddUpdate) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

type CommandRename struct {
	NombreSector         string   `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase           string   `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	NuevoNombre          string   `protobuf:"bytes,3,opt,name=nuevo_nombre,json=nuevoNombre,proto3" json:"nuevo_nombre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRename) Reset()         { *m = CommandRename{} }
func (m *CommandRename) String() string { return proto.CompactTextString(m) }
func (*CommandRename) ProtoMessage()    {}
func (*CommandRename) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc17cb2a757cc3a9, []int{2}
}

func (m *CommandRename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRename.Unmarshal(m, b)
}
func (m *CommandRename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRename.Marshal(b, m, deterministic)
}
func (m *CommandRename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRename.Merge(m, src)
}
func (m *CommandRename) XXX_Size() int {
	return xxx_messageInfo_CommandRename.Size(m)
}
func (m *CommandRename) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRename.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRename proto.InternalMessageInfo

func (m *CommandRename) GetNombreSector() string {
	if m != nil {
		return m.NombreSector
	}
	return ""
}

func (m *CommandRename) GetNombreBase() string {
	if m != nil {
		return m.NombreBase
	}
	return ""
}

func (m *CommandRename) GetNuevoNombre() string {
	if m != nil {
		return m.NuevoNombre
	}
	return ""
}

type CommandDelete struct {
	NombreSector         string   `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase           string   `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandDelete) Reset()         { *m = CommandDelete{} }
func (m *CommandDelete) String() string { return proto.CompactTextString(m) }
func (*CommandDelete) ProtoMessage()    {}
func (*CommandDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc17cb2a757cc3a9, []int{3}
}

func (m *CommandDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDelete.Unmarshal(m, b)
}
func (m *CommandDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDelete.Marshal(b, m, deterministic)
}
func (m *CommandDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDelete.Merge(m, src)
}
func (m *CommandDelete) XXX_Size() int {
	return xxx_messageInfo_CommandDelete.Size(m)
}
func (m *CommandDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDelete.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDelete proto.InternalMessageInfo

func (m *CommandDelete) GetNombreSector() string {
	if m != nil {
		return m.NombreSector
	}
	return ""
}

func (m *CommandDelete) GetNombreBase() string {
	if m != nil {
		return m.NombreBase
	}
	return ""
}

type CommandGet struct {
	NombreSector         string   `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase           string   `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandGet) Reset()         { *m = CommandGet{} }
func (m *CommandGet) String() string { return proto.CompactTextString(m) }
func (*CommandGet) ProtoMessage()    {}
func (*CommandGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc17cb2a757cc3a9, []int{4}
}

func (m *CommandGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandGet.Unmarshal(m, b)
}
func (m *CommandGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandGet.Marshal(b, m, deterministic)
}
func (m *CommandGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandGet.Merge(m, src)
}
func (m *CommandGet) XXX_Size() int {
	return xxx_messageInfo_CommandGet.Size(m)
}
func (m *CommandGet) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandGet.DiscardUnknown(m)
}

var xxx_messageInfo_CommandGet proto.InternalMessageInfo

func (m *CommandGet) GetNombreSector() string {
	if m != nil {
		return m.NombreSector
	}
	return ""
}

func (m *CommandGet) GetNombreBase() string {
	if m != nil {
		return m.NombreBase
	}
	return ""
}

func init() {
	proto.RegisterType((*Mensaje)(nil), "grpc.Mensaje")
	proto.RegisterType((*CommandAddUpdate)(nil), "grpc.CommandAddUpdate")
	proto.RegisterType((*CommandRename)(nil), "grpc.CommandRename")
	proto.RegisterType((*CommandDelete)(nil), "grpc.CommandDelete")
	proto.RegisterType((*CommandGet)(nil), "grpc.CommandGet")
}

func init() { proto.RegisterFile("proto/base.proto", fileDescriptor_dc17cb2a757cc3a9) }

var fileDescriptor_dc17cb2a757cc3a9 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x6f, 0xda, 0x40,
	0x10, 0x85, 0x05, 0x6d, 0xa9, 0x3a, 0xc6, 0x2d, 0xda, 0x56, 0x08, 0xf5, 0xd2, 0xe2, 0x5e, 0x1a,
	0x21, 0xd9, 0x51, 0xc8, 0x21, 0x39, 0x42, 0x50, 0x50, 0x0e, 0xe4, 0x60, 0x44, 0x0e, 0x5c, 0xd0,
	0xd8, 0x1e, 0x39, 0x4e, 0xec, 0x5d, 0xb4, 0xbb, 0x46, 0x51, 0x7e, 0x5f, 0x7e, 0x58, 0xc4, 0xee,
	0x2a, 0x12, 0x56, 0x0e, 0x39, 0x70, 0xb2, 0xe7, 0xcd, 0xbc, 0xfd, 0x3c, 0x7e, 0x5a, 0xe8, 0x6d,
	0xa5, 0xd0, 0x22, 0x4a, 0x50, 0x51, 0x68, 0x5e, 0xd9, 0xe7, 0x5c, 0x6e, 0xd3, 0x60, 0x08, 0x5f,
	0x17, 0xc4, 0x15, 0x3e, 0x10, 0xeb, 0x43, 0x87, 0x8b, 0x2a, 0x91, 0x34, 0x68, 0xfd, 0x6d, 0xfd,
	0xff, 0x16, 0xbb, 0x2a, 0xe0, 0xd0, 0xbb, 0x12, 0x55, 0x85, 0x3c, 0x9b, 0x64, 0xd9, 0x6a, 0x9b,
	0xa1, 0x26, 0xf6, 0x0f, 0x7c, 0xdb, 0xdd, 0x28, 0x4a, 0xb5, 0x90, 0xce, 0xd2, 0xb5, 0xe2, 0xd2,
	0x68, 0xec, 0x0f, 0x78, 0x6e, 0x68, 0x8f, 0x1d, 0xb4, 0xcd, 0x08, 0x58, 0x69, 0x8a, 0x8a, 0xd8,
	0x2f, 0xf8, 0xb2, 0xc3, 0x52, 0xc8, 0xc1, 0x27, 0xd3, 0xb2, 0x45, 0xf0, 0x04, 0xbe, 0xe3, 0xc5,
	0xc4, 0xb1, 0x3a, 0x16, 0x6c, 0x08, 0x5d, 0x5e, 0xd3, 0x4e, 0x6c, 0xdc, 0x92, 0x96, 0xe9, 0x19,
	0xed, 0xd6, 0x6e, 0xba, 0x7a, 0x23, 0xcf, 0xa8, 0xa4, 0x63, 0xad, 0x19, 0xc4, 0x00, 0xee, 0xd8,
	0x39, 0xe9, 0xe3, 0x9c, 0x79, 0xf6, 0xd2, 0x86, 0xef, 0x0b, 0x52, 0x0a, 0x73, 0x5a, 0x92, 0xdc,
	0x15, 0x29, 0xb1, 0x11, 0x78, 0x37, 0x5c, 0x93, 0x4c, 0xb1, 0x4a, 0x0a, 0xc1, 0xfc, 0x70, 0x1f,
	0x70, 0xe8, 0xd2, 0xfd, 0x7d, 0x58, 0xb2, 0x73, 0xf0, 0x26, 0xb9, 0xa4, 0x1c, 0xa5, 0xf9, 0x39,
	0x7d, 0xdb, 0x6d, 0xe6, 0xdc, 0x74, 0x8d, 0xc1, 0x8f, 0xc9, 0x7c, 0x85, 0xf3, 0xfd, 0x3c, 0xf0,
	0xd9, 0xbc, 0x9a, 0xa6, 0x0b, 0xf8, 0x31, 0x49, 0x75, 0x8d, 0x65, 0xf1, 0x8c, 0xf2, 0x6e, 0x1f,
	0xf1, 0x47, 0x71, 0xa7, 0x00, 0x53, 0x21, 0xdf, 0x67, 0xd9, 0x84, 0x9a, 0x8e, 0x10, 0xbc, 0x39,
	0xe9, 0xa5, 0x28, 0x33, 0xcc, 0x84, 0x62, 0xbd, 0x03, 0xcb, 0x9c, 0x74, 0x63, 0x7e, 0x3a, 0x5a,
	0x9f, 0xe4, 0x85, 0xbe, 0xaf, 0x93, 0x30, 0x15, 0x55, 0x74, 0x2d, 0x91, 0xaf, 0x1f, 0x2f, 0xa3,
	0x12, 0x93, 0xf1, 0xac, 0x50, 0x5a, 0x16, 0x49, 0x5d, 0x64, 0x42, 0x45, 0xe6, 0xc6, 0x24, 0x1d,
	0xf3, 0x18, 0xbf, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xf8, 0xf4, 0x1e, 0x4c, 0x03, 0x00, 0x00,
}
